In [1]:
import tensorflow as tf
import numpy as np

In [2]:
n1 = [[1.0, 2.0],[3.0, 4.0]]

In [3]:
n2 = np.array([[1.0,2.0],[3.0,4.0]], dtype=np.float32)

In [4]:
n3 = tf.constant([[1.0, 2.0],[3.0,4.0]])

In [5]:
print(type(n1))
print(type(n2))
print(type(n3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [6]:
t1 = tf.convert_to_tensor(n1, dtype=tf.float32)
t2 = tf.convert_to_tensor(n2, dtype=tf.float32)
t3 = tf.convert_to_tensor(n3, dtype=tf.float32)

In [7]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [8]:
n4 = [[1,2,3],[4,5,6]]
n4 = tf.negative(n4)

In [9]:
print(n4)

Tensor("Neg:0", shape=(2, 3), dtype=int32)


In [10]:
n5 = [[1,2,3],[4,5,6]]
sess = tf.InteractiveSession()
n5 = tf.negative(n5)
print(n5.eval())
sess.close()

[[-1 -2 -3]
 [-4 -5 -6]]


In [11]:
n6 = tf.constant([[1.,2.]])
neg_opt = tf.negative(n6)
print(neg_opt)
with tf.Session() as sess:
    result = sess.run(neg_opt)
print(result)

Tensor("Neg_2:0", shape=(1, 2), dtype=float32)
[[-1. -2.]]


(-b + sqrt(b*b-4*a*c)) / 2 * a

In [12]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = tf.placeholder(tf.float32)
four = tf.constant(4.0)
two = tf.constant(2.0)
b_neg = tf.negative(b)
disc = tf.sqrt(tf.subtract(tf.pow(b,two), tf.multiply(tf.multiply(tf.negative(four),a),2)))
out = tf.divide(disc,tf.multiply(two,a))
init = tf.global_variables_initializer()
with tf.Session() as session:
    file_writer = tf.summary.FileWriter('graph', session.graph)
    session.run(init)
    result = session.run(out,{a:2.0,b:3.0,c:4.0})
    print(result)

1.25


area = square(Diameter/2) * Pi

In [13]:
Pi = tf.constant(tf.divide(22,7))
diameter = tf.placeholder(tf.float32)
half = tf.constant(2.0,tf.float32)
r = tf.divide(diameter, half)
area = tf.multiply(tf.square(r),Pi)
with tf.Session() as session:
    file_writer = tf.summary.FileWriter('graph', session.graph)
    result = session.run(area, {diameter:[16]})
print("area", result)

area [ 201.14285278]
